
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 41;
  public static final int PAR2 = 24;
  public static final int PAR1 = 23;
  public static final int TYPE_BOOLEAN = 14;
  public static final int MULT = 17;
  public static final int TYPE_DOUBLE = 11;
  public static final int CONST = 44;
  public static final int CHAR = 5;
  public static final int IMPRIMIR = 9;
  public static final int ENTERO = 3;
  public static final int XOR = 38;
  public static final int CONTINUE = 52;
  public static final int ID_VARIABLE = 6;
  public static final int FOR = 49;
  public static final int MATCH = 48;
  public static final int LLAV2 = 26;
  public static final int LLAV1 = 25;
  public static final int FINCADENA = 42;
  public static final int NOT = 39;
  public static final int AND = 37;
  public static final int IGUAL = 29;
  public static final int OR = 36;
  public static final int DIV = 18;
  public static final int INCREMENTO = 21;
  public static final int TYPE_INT = 10;
  public static final int IF = 46;
  public static final int UMENOS = 28;
  public static final int IGUAL_IGUAL = 30;
  public static final int EOF = 0;
  public static final int DECIMAL = 4;
  public static final int TRUE = 7;
  public static final int DECREMENTO = 22;
  public static final int error = 1;
  public static final int CADENA = 2;
  public static final int DEFAULT_MATCH = 27;
  public static final int MODULO = 20;
  public static final int MENOS = 16;
  public static final int MAYOR_QUE = 34;
  public static final int BREAK = 43;
  public static final int VOID = 53;
  public static final int TYPE_CHAR = 12;
  public static final int POTENCIA = 19;
  public static final int FLECHA = 40;
  public static final int DIFERENTE_DE = 31;
  public static final int ELSE = 47;
  public static final int TYPE_STRING = 13;
  public static final int WHILE = 50;
  public static final int MAYOR_IGUAL = 35;
  public static final int MENOR_QUE = 32;
  public static final int MENOR_IGUAL = 33;
  public static final int FALSE = 8;
  public static final int VAR = 45;
  public static final int DO = 51;
  public static final int MAS = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "CHAR",
  "ID_VARIABLE",
  "TRUE",
  "FALSE",
  "IMPRIMIR",
  "TYPE_INT",
  "TYPE_DOUBLE",
  "TYPE_CHAR",
  "TYPE_STRING",
  "TYPE_BOOLEAN",
  "MAS",
  "MENOS",
  "MULT",
  "DIV",
  "POTENCIA",
  "MODULO",
  "INCREMENTO",
  "DECREMENTO",
  "PAR1",
  "PAR2",
  "LLAV1",
  "LLAV2",
  "DEFAULT_MATCH",
  "UMENOS",
  "IGUAL",
  "IGUAL_IGUAL",
  "DIFERENTE_DE",
  "MENOR_QUE",
  "MENOR_IGUAL",
  "MAYOR_QUE",
  "MAYOR_IGUAL",
  "OR",
  "AND",
  "XOR",
  "NOT",
  "FLECHA",
  "DOSPUNTOS",
  "FINCADENA",
  "BREAK",
  "CONST",
  "VAR",
  "IF",
  "ELSE",
  "MATCH",
  "FOR",
  "WHILE",
  "DO",
  "CONTINUE",
  "VOID"
  };
}

