
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 44;
  public static final int PAR2 = 28;
  public static final int PAR1 = 27;
  public static final int TYPE_BOOLEAN = 15;
  public static final int COR2 = 30;
  public static final int MULT = 21;
  public static final int COR1 = 29;
  public static final int TYPE_DOUBLE = 12;
  public static final int CONST = 16;
  public static final int CHAR = 5;
  public static final int IMPRIMIR = 10;
  public static final int ENTERO = 3;
  public static final int XOR = 41;
  public static final int ID_VARIABLE = 6;
  public static final int NOT = 42;
  public static final int AND = 40;
  public static final int FINCADENA = 9;
  public static final int IGUAL = 32;
  public static final int OR = 39;
  public static final int DIV = 22;
  public static final int INCREMENTO = 25;
  public static final int TYPE_INT = 11;
  public static final int IF = 18;
  public static final int UMENOS = 31;
  public static final int IGUAL_IGUAL = 33;
  public static final int EOF = 0;
  public static final int DECIMAL = 4;
  public static final int TRUE = 7;
  public static final int DECREMENTO = 26;
  public static final int error = 1;
  public static final int CADENA = 2;
  public static final int MODULO = 24;
  public static final int MENOS = 20;
  public static final int MAYOR_QUE = 37;
  public static final int TYPE_CHAR = 13;
  public static final int POTENCIA = 23;
  public static final int FLECHA = 43;
  public static final int DIFERENTE_DE = 34;
  public static final int TYPE_STRING = 14;
  public static final int MAYOR_IGUAL = 38;
  public static final int MENOR_QUE = 35;
  public static final int MENOR_IGUAL = 36;
  public static final int FALSE = 8;
  public static final int VAR = 17;
  public static final int MAS = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "CHAR",
  "ID_VARIABLE",
  "TRUE",
  "FALSE",
  "FINCADENA",
  "IMPRIMIR",
  "TYPE_INT",
  "TYPE_DOUBLE",
  "TYPE_CHAR",
  "TYPE_STRING",
  "TYPE_BOOLEAN",
  "CONST",
  "VAR",
  "IF",
  "MAS",
  "MENOS",
  "MULT",
  "DIV",
  "POTENCIA",
  "MODULO",
  "INCREMENTO",
  "DECREMENTO",
  "PAR1",
  "PAR2",
  "COR1",
  "COR2",
  "UMENOS",
  "IGUAL",
  "IGUAL_IGUAL",
  "DIFERENTE_DE",
  "MENOR_QUE",
  "MENOR_IGUAL",
  "MAYOR_QUE",
  "MAYOR_IGUAL",
  "OR",
  "AND",
  "XOR",
  "NOT",
  "FLECHA",
  "DOSPUNTOS"
  };
}

